version: '2.4'
services:
  coolhub-user-db:
    image: postgres:11.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - type: volume
        source: coolhub-user-postgresql-data-volume
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgresql_init_scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  coolhub-user-postgresql-data-volume:
    name: coolhub-user-postgresql11-data

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 200.202.0.0/16
          gateway: 200.202.0.1
