name: CoolHub build and push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (coolhub-user)
        id: coolhub-user
        uses: docker/metadata-action@v4
        with:
          images: |
            hronom/coolhub-user
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image (coolhub-user)
        uses: docker/build-push-action@v2
        with:
          context: ./coolhub-user
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.coolhub-user.outputs.tags }}
          labels: ${{ steps.coolhub-user.outputs.labels }}

      - name: Docker meta (coolhub-post)
        id: coolhub-post
        uses: docker/metadata-action@v4
        with:
          images: |
            hronom/coolhub-post
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image (coolhub-post)
        uses: docker/build-push-action@v2
        with:
          context: ./coolhub-post
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.coolhub-post.outputs.tags }}
          labels: ${{ steps.coolhub-post.outputs.labels }}

      - name: Docker meta (coolhub-ui)
        id: coolhub-ui
        uses: docker/metadata-action@v4
        with:
          images: |
            hronom/coolhub-ui
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image (coolhub-ui)
        uses: docker/build-push-action@v2
        with:
          context: ./coolhub-ui
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.coolhub-ui.outputs.tags }}
          labels: ${{ steps.coolhub-ui.outputs.labels }}
